# Autogenerated by make-sphinx-conf.py -- do not edit!
# Command line: ../sphinx_helpers/make-sphinx-conf.py ch_frb_l1

import os
import sys

# From command line
project = u'ch_frb_l1'

# Added by KMS
autoclass_content = 'both'
autodoc_default_flags = [ 'inherited-members' ]
html_show_copyright = False
html_show_sphinx = False
html_show_sourcelink = False

# From sphinx-quickstart
extensions = [ 'sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx.ext.autosectionlabel' ]
source_suffix = '.rst'
master_doc = 'index'
html_theme = 'sphinx_rtd_theme'
